<?php
if (! defined('ABSPATH')) { exit; }
if (!current_user_can('pms_manage_expenses') && !current_user_can('pms_submit_expenses')) { wp_die(__('You do not have permission to view this page.','pms')); }
$can_manage=current_user_can('pms_manage_expenses'); $today=current_time('Y-m-d'); $tab=isset($_GET['expense_tab'])?sanitize_key(wp_unslash($_GET['expense_tab'])):'overview';
$tabs=$can_manage?['overview'=>['Overview','dashicons-chart-pie'],'expenses'=>['Expenses','dashicons-list-view'],'approvals'=>['Approvals','dashicons-yes-alt'],'reports'=>['Expense Reports','dashicons-chart-bar']]:['expenses'=>['My Expenses','dashicons-list-view']];
if(!isset($tabs[$tab])){$tab=$can_manage?'overview':'expenses';} $notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['pms_expense_action'])){check_admin_referer('pms_expenses_manage','pms_expenses_nonce');$a=sanitize_key(wp_unslash($_POST['pms_expense_action']));
 if($a==='create'){ $id=PMS_Expenses::create(['employee_id'=>$can_manage&&!empty($_POST['employee_id'])?absint($_POST['employee_id']):get_current_user_id(),'category'=>sanitize_text_field(wp_unslash($_POST['category']??'Other')),'description'=>sanitize_textarea_field(wp_unslash($_POST['description']??'')),'amount'=>(float)($_POST['amount']??0),'currency'=>sanitize_text_field(wp_unslash($_POST['currency']??'USD')),'expense_date'=>sanitize_text_field(wp_unslash($_POST['expense_date']??$today)),'receipt_url'=>esc_url_raw(wp_unslash($_POST['receipt_url']??'')),'notes'=>sanitize_textarea_field(wp_unslash($_POST['notes']??''))]);$notice=$id?__('Expense submitted successfully.','pms'):'';$error=$id?'':__('The expense could not be submitted. Check the amount and description.','pms');$tab='expenses';}
 elseif($a==='status'&&$can_manage){$ok=PMS_Expenses::set_status(absint($_POST['expense_id']??0),sanitize_key(wp_unslash($_POST['status']??'')));$notice=$ok?__('Expense status updated.','pms'):__('The expense status could not be updated.','pms');$tab='approvals';}}
$report=PMS_Expenses::report();$rows=PMS_Expenses::rows(!$can_manage);$all=$can_manage?PMS_Expenses::rows():$rows;$employees=$can_manage?PMS_Roles::get_pms_people():[];$cats=['Travel','Meals','Transport','Office','Equipment','Utilities','Training','Other'];
$money=static function($a,$c='USD'){return esc_html(strtoupper((string)$c).' '.number_format((float)$a,2));};
?>
<div class="pms-expenses"><div class="pms-page-header"><div><p class="pms-eyebrow"><?php esc_html_e('Finance','pms'); ?></p><h1><?php esc_html_e('Expenses','pms'); ?></h1><p class="pms-page-description"><?php esc_html_e('Record expenses, review approvals and monitor spending.','pms'); ?></p></div></div>
<?php if($notice):?><div class="pms-notice pms-notice-success"><?php echo esc_html($notice);?></div><?php endif;?><?php if($error):?><div class="pms-notice pms-notice-error"><?php echo esc_html($error);?></div><?php endif;?>
<div class="pms-payroll-tabs pms-expense-tabs"><?php foreach($tabs as $k=>$item):?><a class="<?php echo $tab===$k?'is-active':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=pms-expenses&expense_tab='.$k));?>"><span class="dashicons <?php echo esc_attr($item[1]);?>"></span><?php echo esc_html($item[0]);?></a><?php endforeach;?></div>
<?php if($tab==='overview'):?><div class="pms-kpi-grid pms-expense-kpis"><div class="pms-kpi-card"><small>EXPENSES</small><strong><?php echo esc_html($report['count']);?></strong></div><div class="pms-kpi-card"><small>TOTAL</small><strong><?php echo $money($report['total']);?></strong></div><div class="pms-kpi-card"><small>PENDING</small><strong><?php echo $money($report['pending']);?></strong></div><div class="pms-kpi-card"><small>APPROVED</small><strong><?php echo $money($report['approved']);?></strong></div></div><?php endif;?>
<?php if($tab==='expenses'):?>
<div class="pms-panel pms-form-panel"><div class="pms-section-head"><div><h2><?php echo $can_manage?esc_html__('Record Expense','pms'):esc_html__('Submit Expense','pms');?></h2></div></div><form method="post"><?php wp_nonce_field('pms_expenses_manage','pms_expenses_nonce');?><input type="hidden" name="pms_expense_action" value="create"><div class="pms-form-grid">
<?php if($can_manage):?><label>Employee<select class="pms-input" name="employee_id"><option value="<?php echo get_current_user_id();?>">Myself</option><?php foreach($employees as $e):?><?php if((int)$e->ID!==get_current_user_id()):?><option value="<?php echo (int)$e->ID;?>"><?php echo esc_html($e->display_name);?></option><?php endif;?><?php endforeach;?></select></label><?php endif;?>
<label>Category<select class="pms-input" name="category"><?php foreach($cats as $c):?><option><?php echo esc_html($c);?></option><?php endforeach;?></select></label><label>Amount<input class="pms-input" type="number" name="amount" min="0.01" step="0.01" required></label><label>Currency<input class="pms-input" name="currency" value="USD" required></label><label>Expense Date<input class="pms-input" type="date" name="expense_date" value="<?php echo esc_attr($today);?>" required></label><label>Receipt URL<input class="pms-input" type="url" name="receipt_url"></label></div><label class="pms-form-field">Description<textarea class="pms-input" name="description" rows="3" required></textarea></label><label class="pms-form-field">Notes<textarea class="pms-input" name="notes" rows="3"></textarea></label><button class="pms-btn pms-btn-primary" type="submit">Submit Expense</button></form></div>
<div class="pms-panel"><div class="pms-section-head"><h2><?php echo $can_manage?esc_html__('Expense Register','pms'):esc_html__('My Expenses','pms');?></h2></div><div class="pms-table-wrap"><table class="pms-table"><thead><tr><th>Expense</th><th>Employee</th><th>Category</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?php echo esc_html($r->expense_number);?></strong><br><small><?php echo esc_html($r->description);?></small></td><td><?php echo esc_html($r->employee_name?:'—');?></td><td><?php echo esc_html($r->category);?></td><td><?php echo esc_html($r->expense_date);?></td><td><?php echo $money($r->amount,$r->currency);?></td><td><span class="pms-status"><?php echo esc_html(ucfirst($r->status));?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="pms-empty">No expenses recorded yet.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
<?php if($tab==='approvals'):?><div class="pms-panel"><div class="pms-section-head"><div><h2>Expense Approvals</h2><p>Approve, reject or mark approved expenses as paid.</p></div></div><div class="pms-table-wrap"><table class="pms-table"><thead><tr><th>Expense</th><th>Employee</th><th>Category</th><th>Date</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($all as $r):?><tr><td><strong><?php echo esc_html($r->expense_number);?></strong><br><small><?php echo esc_html($r->description);?></small></td><td><?php echo esc_html($r->employee_name?:'—');?></td><td><?php echo esc_html($r->category);?></td><td><?php echo esc_html($r->expense_date);?></td><td><?php echo $money($r->amount,$r->currency);?></td><td><span class="pms-status"><?php echo esc_html(ucfirst($r->status));?></span></td><td><form method="post" class="pms-inline-form"><?php wp_nonce_field('pms_expenses_manage','pms_expenses_nonce');?><input type="hidden" name="pms_expense_action" value="status"><input type="hidden" name="expense_id" value="<?php echo (int)$r->id;?>"><?php if($r->status==='pending'):?><button class="pms-btn pms-btn-small pms-btn-primary" name="status" value="approved">Approve</button><button class="pms-btn pms-btn-small pms-btn-danger" name="status" value="rejected">Reject</button><?php elseif($r->status==='approved'):?><button class="pms-btn pms-btn-small" name="status" value="paid">Mark Paid</button><?php endif;?></form></td></tr><?php endforeach;?><?php if(!$all):?><tr><td colspan="7" class="pms-empty">No expenses to review.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
<?php if($tab==='reports'):?><div class="pms-kpi-grid pms-expense-kpis"><div class="pms-kpi-card"><small>RECORDED</small><strong><?php echo $money($report['total']);?></strong></div><div class="pms-kpi-card"><small>PENDING</small><strong><?php echo $money($report['pending']);?></strong></div><div class="pms-kpi-card"><small>APPROVED</small><strong><?php echo $money($report['approved']);?></strong></div><div class="pms-kpi-card"><small>REJECTED</small><strong><?php echo $money($report['rejected']);?></strong></div></div><div class="pms-panel"><div class="pms-section-head"><h2>Expense Reports</h2></div><div class="pms-report-bars"><?php foreach($report['by_category'] as $cat):$w=$report['approved']>0?min(100,((float)$cat->total/$report['approved'])*100):0;?><div><span><?php echo esc_html($cat->category);?></span><b style="width:<?php echo esc_attr($w);?>%"></b><strong><?php echo $money($cat->total);?></strong></div><?php endforeach;?><?php if(!$report['by_category']):?><p class="pms-empty">No approved expenses to report yet.</p><?php endif;?></div></div><?php endif;?>
</div>