<?php
if (! defined('ABSPATH')) { exit; }
if (! current_user_can('pms_manage_inventory')) { wp_die(__('You do not have permission to view this page.', 'pms')); }
$tab=isset($_GET['inventory_tab'])?sanitize_key(wp_unslash($_GET['inventory_tab'])):'overview';
$tabs=['overview'=>['Overview','dashicons-chart-pie'],'items'=>['Items','dashicons-archive'],'stock'=>['Stock Movements','dashicons-update'],'suppliers'=>['Suppliers','dashicons-groups']];
if(!isset($tabs[$tab]))$tab='overview'; $notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){check_admin_referer('pms_inventory_manage','pms_inventory_nonce');$a=sanitize_key(wp_unslash($_POST['inventory_action']??''));
 if($a==='item'){ $id=PMS_Inventory::create_item($_POST);$notice=$id?__('Item created.','pms'):__('Could not create item. Check the item name and SKU.','pms');$tab='items';}
 elseif($a==='supplier'){ $id=PMS_Inventory::create_supplier($_POST);$notice=$id?__('Supplier created.','pms'):__('Could not create supplier.','pms');$tab='suppliers';}
 elseif($a==='movement'){ $ok=PMS_Inventory::movement(absint($_POST['item_id']??0),sanitize_key(wp_unslash($_POST['movement_type']??'')),(float)($_POST['quantity']??0),(float)($_POST['unit_cost']??0),sanitize_text_field(wp_unslash($_POST['reference']??'')),sanitize_textarea_field(wp_unslash($_POST['notes']??'')));$notice=$ok?__('Stock updated.','pms'):__('Stock movement could not be applied. Check the quantity and available stock.','pms');$tab='stock';}
}
$items=PMS_Inventory::items();$suppliers=PMS_Inventory::suppliers();$moves=PMS_Inventory::recent_movements();$summary=PMS_Inventory::summary();
?>
<div class="pms-inventory"><div class="pms-page-header"><div><p class="pms-eyebrow">Operations</p><h1>Inventory</h1><p class="pms-page-description">Manage items, stock levels and suppliers.</p></div></div>
<?php if($notice):?><div class="pms-notice pms-notice-success"><?php echo esc_html($notice);?></div><?php endif;?><?php if($error):?><div class="pms-notice pms-notice-error"><?php echo esc_html($error);?></div><?php endif;?>
<div class="pms-payroll-tabs pms-inventory-tabs"><?php foreach($tabs as $k=>$t):?><a class="<?php echo $tab===$k?'is-active':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=pms-inventory&inventory_tab='.$k));?>"><span class="dashicons <?php echo esc_attr($t[1]);?>"></span><?php echo esc_html($t[0]);?></a><?php endforeach;?></div>
<?php if($tab==='overview'):?><div class="pms-kpi-grid pms-inventory-kpis"><div class="pms-kpi-card"><small>ITEMS</small><strong><?php echo $summary['items'];?></strong></div><div class="pms-kpi-card"><small>STOCK VALUE</small><strong><?php echo esc_html(number_format($summary['stock_value'],2));?></strong></div><div class="pms-kpi-card"><small>LOW STOCK</small><strong><?php echo $summary['low_stock'];?></strong></div><div class="pms-kpi-card"><small>SUPPLIERS</small><strong><?php echo $summary['suppliers'];?></strong></div></div><?php endif;?>
<?php if($tab==='items'):?><div class="pms-panel pms-form-panel"><div class="pms-section-head"><h2>Add Inventory Item</h2></div><form method="post"><?php wp_nonce_field('pms_inventory_manage','pms_inventory_nonce');?><input type="hidden" name="inventory_action" value="item"><div class="pms-form-grid"><label>SKU<input class="pms-input" name="sku"></label><label>Item Name<input class="pms-input" name="name" required></label><label>Category<input class="pms-input" name="category"></label><label>Supplier<select class="pms-input" name="supplier_id"><option value="">None</option><?php foreach($suppliers as $s):?><option value="<?php echo (int)$s->id;?>"><?php echo esc_html($s->name);?></option><?php endforeach;?></select></label><label>Unit<input class="pms-input" name="unit" value="unit"></label><label>Cost<input class="pms-input" type="number" step="0.01" min="0" name="cost" value="0"></label><label>Price<input class="pms-input" type="number" step="0.01" min="0" name="price" value="0"></label><label>Opening Stock<input class="pms-input" type="number" step="0.001" min="0" name="stock" value="0"></label><label>Reorder Level<input class="pms-input" type="number" step="0.001" min="0" name="reorder_level" value="0"></label></div><label class="pms-form-field">Description<textarea class="pms-input" name="description" rows="3"></textarea></label><button class="pms-btn pms-btn-primary" type="submit">Add Item</button></form></div>
<div class="pms-panel"><div class="pms-section-head"><h2>Inventory Items</h2></div><div class="pms-table-wrap"><table class="pms-table"><thead><tr><th>SKU</th><th>Item</th><th>Category</th><th>Supplier</th><th>Stock</th><th>Cost</th><th>Price</th><th>State</th></tr></thead><tbody><?php foreach($items as $i):$low=(float)$i->stock<=(float)$i->reorder_level;?><tr><td><strong><?php echo esc_html($i->sku);?></strong></td><td><?php echo esc_html($i->name);?></td><td><?php echo esc_html($i->category?:'—');?></td><td><?php echo esc_html($i->supplier_name?:'—');?></td><td><strong><?php echo esc_html($i->stock);?></strong> <?php echo esc_html($i->unit);?></td><td><?php echo number_format((float)$i->cost,2);?></td><td><?php echo number_format((float)$i->price,2);?></td><td><span class="pms-status <?php echo $low?'pms-inventory-low':'';?>"><?php echo $low?'Low stock':'In stock';?></span></td></tr><?php endforeach;?><?php if(!$items):?><tr><td colspan="8" class="pms-empty">No inventory items yet.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
<?php if($tab==='stock'):?><div class="pms-panel pms-form-panel"><div class="pms-section-head"><h2>Update Stock</h2></div><form method="post"><?php wp_nonce_field('pms_inventory_manage','pms_inventory_nonce');?><input type="hidden" name="inventory_action" value="movement"><div class="pms-form-grid"><label>Item<select class="pms-input" name="item_id" required><?php foreach($items as $i):?><option value="<?php echo (int)$i->id;?>"><?php echo esc_html($i->sku.' — '.$i->name.' ('.$i->stock.')');?></option><?php endforeach;?></select></label><label>Movement<select class="pms-input" name="movement_type"><option value="in">Stock In</option><option value="out">Stock Out</option><option value="adjustment_in">Adjustment In</option><option value="adjustment_out">Adjustment Out</option></select></label><label>Quantity<input class="pms-input" type="number" name="quantity" min="0.001" step="0.001" required></label><label>Unit Cost<input class="pms-input" type="number" name="unit_cost" min="0" step="0.01" value="0"></label><label>Reference<input class="pms-input" name="reference"></label></div><label class="pms-form-field">Notes<textarea class="pms-input" name="notes" rows="3"></textarea></label><button class="pms-btn pms-btn-primary">Update Stock</button></form></div><div class="pms-panel"><div class="pms-section-head"><h2>Recent Stock Movements</h2></div><div class="pms-table-wrap"><table class="pms-table"><thead><tr><th>Item</th><th>Movement</th><th>Quantity</th><th>Reference</th><th>Date</th></tr></thead><tbody><?php foreach($moves as $m):?><tr><td><strong><?php echo esc_html($m->sku);?></strong><br><?php echo esc_html($m->item_name);?></td><td><?php echo esc_html(ucwords(str_replace('_',' ',$m->movement_type)));?></td><td><?php echo esc_html($m->quantity);?></td><td><?php echo esc_html($m->reference?:'—');?></td><td><?php echo esc_html($m->created_at);?></td></tr><?php endforeach;?><?php if(!$moves):?><tr><td colspan="5" class="pms-empty">No stock movements yet.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
<?php if($tab==='suppliers'):?><div class="pms-panel pms-form-panel"><div class="pms-section-head"><h2>Add Supplier</h2></div><form method="post"><?php wp_nonce_field('pms_inventory_manage','pms_inventory_nonce');?><input type="hidden" name="inventory_action" value="supplier"><div class="pms-form-grid"><label>Name<input class="pms-input" name="name" required></label><label>Contact Name<input class="pms-input" name="contact_name"></label><label>Email<input class="pms-input" type="email" name="email"></label><label>Phone<input class="pms-input" name="phone"></label></div><label class="pms-form-field">Address<textarea class="pms-input" name="address" rows="3"></textarea></label><button class="pms-btn pms-btn-primary">Add Supplier</button></form></div><div class="pms-panel"><div class="pms-section-head"><h2>Suppliers</h2></div><div class="pms-table-wrap"><table class="pms-table"><thead><tr><th>Supplier</th><th>Contact</th><th>Email</th><th>Phone</th><th>Status</th></tr></thead><tbody><?php foreach($suppliers as $s):?><tr><td><strong><?php echo esc_html($s->name);?></strong></td><td><?php echo esc_html($s->contact_name?:'—');?></td><td><?php echo esc_html($s->email?:'—');?></td><td><?php echo esc_html($s->phone?:'—');?></td><td>Active</td></tr><?php endforeach;?><?php if(!$suppliers):?><tr><td colspan="5" class="pms-empty">No suppliers yet.</td></tr><?php endif;?></tbody></table></div></div><?php endif;?>
</div>