<?php
if (! defined('ABSPATH')) { exit; }
class PMS_Expenses {
 public static function table(): string { global $wpdb; return $wpdb->prefix . 'pms_expenses'; }
 public static function schema_sql(): string { global $wpdb; $t=self::table(); $c=$wpdb->get_charset_collate(); return "CREATE TABLE {$t} (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, expense_number VARCHAR(64) NOT NULL, employee_id BIGINT UNSIGNED NULL,
 category VARCHAR(100) NOT NULL, description TEXT NOT NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, currency VARCHAR(10) NOT NULL DEFAULT 'USD',
 expense_date DATE NOT NULL, receipt_url TEXT NULL, status VARCHAR(24) NOT NULL DEFAULT 'pending', approved_by BIGINT UNSIGNED NULL,
 approved_at DATETIME NULL, notes TEXT NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NULL, updated_at DATETIME NULL,
 PRIMARY KEY (id), UNIQUE KEY expense_number (expense_number), KEY employee_id (employee_id), KEY category (category), KEY status (status), KEY expense_date (expense_date)
 ) {$c};"; }
 public static function rows(bool $mine=false): array { global $wpdb; $t=self::table(); $where=$mine ? $wpdb->prepare(' WHERE e.employee_id = %d',get_current_user_id()) : ''; return $wpdb->get_results("SELECT e.*,u.display_name AS employee_name FROM {$t} e LEFT JOIN {$wpdb->users} u ON u.ID=e.employee_id{$where} ORDER BY e.expense_date DESC,e.id DESC"); }
 public static function report(): array { global $wpdb; $t=self::table(); $x=$wpdb->get_row("SELECT COUNT(*) count,COALESCE(SUM(amount),0) total,COALESCE(SUM(CASE WHEN status='pending' THEN amount ELSE 0 END),0) pending,COALESCE(SUM(CASE WHEN status='approved' THEN amount ELSE 0 END),0) approved,COALESCE(SUM(CASE WHEN status='rejected' THEN amount ELSE 0 END),0) rejected FROM {$t}"); $cats=$wpdb->get_results("SELECT category,COUNT(*) count,COALESCE(SUM(amount),0) total FROM {$t} WHERE status IN ('approved','paid') GROUP BY category ORDER BY total DESC"); return ['count'=>(int)$x->count,'total'=>(float)$x->total,'pending'=>(float)$x->pending,'approved'=>(float)$x->approved,'rejected'=>(float)$x->rejected,'by_category'=>$cats]; }
 public static function next_number(): string { global $wpdb; $p='EXP-'.gmdate('Y').'-'; $last=$wpdb->get_var($wpdb->prepare("SELECT expense_number FROM ".self::table()." WHERE expense_number LIKE %s ORDER BY id DESC LIMIT 1",$p.'%')); $n=1; if($last && preg_match('/-(\\d+)$/',$last,$m)){ $n=(int)$m[1]+1; } return $p.str_pad((string)$n,5,'0',STR_PAD_LEFT); }
 public static function create(array $d): int { global $wpdb; $employee=!empty($d['employee_id'])?absint($d['employee_id']):get_current_user_id(); $amount=max(0,(float)($d['amount']??0)); $desc=trim((string)($d['description']??'')); if(!$employee||$amount<=0||$desc===''){return 0;} $ok=$wpdb->insert(self::table(),['expense_number'=>sanitize_text_field($d['expense_number']??self::next_number()),'employee_id'=>$employee,'category'=>sanitize_text_field($d['category']??'Other'),'description'=>sanitize_textarea_field($desc),'amount'=>$amount,'currency'=>strtoupper(sanitize_text_field($d['currency']??'USD')),'expense_date'=>sanitize_text_field($d['expense_date']??current_time('Y-m-d')),'receipt_url'=>esc_url_raw($d['receipt_url']??''),'status'=>'pending','notes'=>sanitize_textarea_field($d['notes']??''),'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')],['%s','%d','%s','%s','%f','%s','%s','%s','%s','%s','%d','%s','%s']); return $ok?(int)$wpdb->insert_id:0; }
 public static function set_status(int $id,string $status): bool { global $wpdb; if(!in_array($status,['pending','approved','rejected','paid'],true)){return false;} $d=['status'=>$status,'updated_at'=>current_time('mysql')]; $f=['%s','%s']; if($status==='approved'){ $d['approved_by']=get_current_user_id();$d['approved_at']=current_time('mysql');$f[]='%d';$f[]='%s'; } return (bool)$wpdb->update(self::table(),$d,['id'=>$id],$f,['%d']); }
}